### ISSUE TITLE
feat/wizzard: Multiline elements not proper resizeable

### ISSUE THREAD

**Issue by tschmidtb51** [secvisogram/secvisogram#397]
Multiline elements can't be resized to the right (even if there is plenty of space as in `/document/publisher`).

**Comment by cloeser** [comment]
In the first version of the new editor there was no constraint in field size. This lead to columns being super wide or narrow. Since the editor already has to display quite some columns for most of the paths in a csaf document we decided to set a max width.

Not sure how to best handle this. We could maybe increase the max size, but that also means that every column with a multiline input can get wider since the view is generic which leads to more side scrolling.

**Comment by tschmidtb51** [comment]
Would it be possible to only use the max size when a column to the right exists?

**Comment by cloeser** [comment]
My bad, I mixed two things here.
Every input is always on the far right. We will remove the size constraint but keep the min width.
